add more geoip service urls
threefoldtech/zos pull request #2015
Opened 2023-07-31 06:34 UTC by MarioBassem

## Related issues:

- #1887

2023-07-31 06:40 UTC, xmonader commented on pkg/geoip/geoip.go
> +	for i := 0; i < len(geoipURLs); i++ {
why not a for range?

2023-07-31 06:42 UTC, xmonader commented on pkg/geoip/geoip.go
> +		defer resp.Body.Close()
this won't be properly handled (you're calling the defer within a for-loop)

2023-07-31 06:46 UTC, xmonader reviewed
I was expecting that we would fire up multiple requests in the background against the 3 geoip services and as soon one of the returns a healthy result we can use it, but  @muhamadazmy can decide how to approach it properly

2023-07-31 07:33 UTC, xmonader commented on pkg/geoip/geoip.go
> +func getLocation(url string) (Location, error) {
see how many Location{} ? can use a named parameter or even create it on the top of the function and reuse it

2023-07-31 07:33 UTC, xmonader commented on pkg/geoip/geoip.go
> +			log.Err(err).Msg("failed to fetch location. retrying...")
encode which broken service

2023-07-31 07:35 UTC, xmonader commented on pkg/geoip/geoip.go
> +func getLocation(url string) (Location, error) {
can use a better name for url ( e.g geoIPService) because it's not apparent from the first sight what url that is

2023-07-31 07:45 UTC, xmonader approved these changes, later dismissed

2023-07-31 08:08 UTC, muhamadazmy requested changes

2023-07-31 08:08 UTC, muhamadazmy commented on pkg/geoip/geoip.go
> +	geoipURLs := []string{"https://geoip.grid.tf/", "https://02.geoip.grid.tf/", "https://03.geoip.grid.tf/"}
can this be defined in the global scope (outside the function body) not on the stack. it's more of a constant than a variable. like

```go
var (
   geoipURLs = []string{...}
)
```

2023-07-31 08:08 UTC, muhamadazmy commented on pkg/geoip/geoip.go
> +			log.Err(err).Msgf("failed to fetch location from geoip service %s. retrying...", url)
the log here is kinda misleading, we are not `retrying` instead we are trying a completely different url. Instead the error should show which url is not working + the cause. Also please use the structured logs correctly. Use the available, Str, Int, etc.. not formatting as much as possiblel

```go
log.Err(err).Str("url", url).Msg("failed to fetch location from geoip service")
```

Is more correct form than the one in code

2023-08-09 11:19 UTC, muhamadazmy approved these changes
Please merge only after testing

2023-08-09 11:53 UTC, merged