add block cache for upgrade service
threefoldtech/zos pull request #2032
Opened 2023-08-28 06:42 UTC by MarioBassem

2023-08-28 18:09 UTC, xmonader commented on pkg/upgrade/cache.go
> +	DefaultBlockSize = 512 //KB
Please add unit suffix e.g DefaultBlockSizeKB

2023-08-28 18:11 UTC, xmonader commented on pkg/upgrade/cache.go
> +	DefaultBlockSize = 512 //KB
also noticed these constants are also used internally in functions and there's no way to override them, please make them unexported

2023-08-28 18:12 UTC, xmonader commented on pkg/upgrade/cache.go
> +	cache     string
is that cacheDir?

2023-08-28 18:12 UTC, xmonader commented on pkg/upgrade/cache.go
> +	workers   int
change to numWorkers

2023-08-28 18:12 UTC, xmonader commented on pkg/upgrade/cache.go
> +	blockSize uint64
add unit here please, Is it byte, kb, .. etc

2023-08-28 18:13 UTC, xmonader commented on pkg/upgrade/cache.go
> +// Downloader allows to get some data blocks using a pool of workers
This is a concrete type, I believe the documentation needs to be more specific

2023-08-29 20:23 UTC, xmonader requested changes

2023-08-29 20:23 UTC, xmonader commented on pkg/upgrade/cache.go
>  	apply(d *Downloader)
it's not done like that, please make sure to remove the interface, 

you can have a new type e.g DownloaderOption that's a mutation method func(d  *Downloader)

and create function e.g WtihNumWorkers e.g

```go
func WithNumWorkers(n int) func(*Downloader) {
            return func(d *Downloader){ 
                    d.numWorkers = n
            
            }
}

```


Please don't introduce interfaces that're not needed

2023-08-29 20:25 UTC, xmonader commented on pkg/upgrade/cache.go
>  	apply(d *Downloader)
we use that in order not to break the API, while this is all internal it's fine to have the numworker in the factory function, or even if the type is simple an depends on the zero value you can directly use it and have the fields exported without tons of chores.

2023-08-30 11:24 UTC, muhamadazmy submitted a review, later dismissed

2023-08-30 11:32 UTC, xmonader approved these changes

2023-08-30 11:42 UTC, merged