set default value of 5GB for cache size it is zero
threefoldtech/zos pull request #2129
Opened 2023-11-20 19:54 UTC by Omarabdul3ziz

### Description
set default value of 5GB for cache size it is zero

### Related Issues
- https://github.com/threefoldtech/zos/issues/2128

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2023-11-20 20:15 UTC, xmonader commented
Did you try to mount other disks in the new VM? other than the ones used by the first one? check vm.sh first please this seems like hiding a problem

2023-11-21 08:58 UTC, muhamadazmy requested changes

2023-11-21 08:58 UTC, muhamadazmy commented on pkg/storage/storage.go
> +		usage.Size = 5
5 what? :D 
When i said set the size of the cache to 5. I meant 5gib. and that's not just a random number, it's the sizeMultiplier. 

But anyway, this is not exactly i wanted it to be done. The idea is if the cache.Size is not set (no limit) I wanted to make sure the `limit` is actually set first, before you even try to adjust.

```go
if useage.Size == 0 {
   usge.Size = max(sizeMultiplier, usage.Excl)
   if err := cache.Limit(usage.Size); err != nil {
       return err
   }
}
// ... rest of the function
```

2023-11-21 08:58 UTC, muhamadazmy commented on pkg/storage/storage.go
> +		usage.Size = 5
To test this, make sure your cache volume has no quota set then restart storaged. then the cache should have some limit

2023-11-22 10:25 UTC, muhamadazmy approved these changes

2023-11-22 10:25 UTC, merged