Add mountpoint cleanup
threefoldtech/zos pull request #2173
Opened 2023-12-19 12:17 UTC by AbdelrahmanElawady

### Description

Cleanup mountpoints every 24hrs

### Related Issues

- #2166

### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstring

2023-12-20 12:40 UTC, muhamadazmy requested changes
After taking a look at this PR and review the flistd code I realised the following:
- The fix implemented has issues as explained in the comments below
- The flistd already has code that works in a safe way (where there is no way a mount/unmount are in progress) but seems that code is not working as expected. 
- Hence the code here should investigate and fix why the `cleanUnusedMounts` function is not doing what it needs to do

the `flistModule.cleanUnusedMounts` function is invoked after a mount and an unmount operation which make it run inside the zbus workers. this makes it safe because flistd only have one workers hence it's grated that there no other mount operations are in progress.

Please then review the code of this function and fix the issues  that cause the clean operation to not work as expected

2023-12-20 12:40 UTC, muhamadazmy commented on pkg/flist/cleanup.go
> +
flistModule already has a `f.isMountpoint()` method !

2023-12-20 12:40 UTC, muhamadazmy commented on pkg/flist/cleanup.go
> +func (f *flistModule) MountsCleaner(ctx context.Context, every time.Duration) {
This is very unsafe procedures. 

this runs in the background in a continues loop. What prevents this from deleting a mountpoint that was just created, just before the filesystem is actually mounted. 

Hence this procedure can cause race conditions and errors that are impossible to debug.

2023-12-20 12:44 UTC, muhamadazmy commented
I already the issue with the function is that it does only clean up of `ro` mounts that are not used by any mount point but does not clean up un-used folders.

It can still go over all possible (as done in the PR) and delete any folder that is not a mount point.
It can also delete all empty ro mount locations that are not mount points

2023-12-31 16:55 UTC, xmonader commented on pkg/flist/cleanup.go
> +			log.Error().Err(err).Msg("failed to clean mountpoint")
include path in the error please

2024-01-10 11:37 UTC, muhamadazmy approved these changes

2024-01-10 11:37 UTC, merged