Add autobuild script
threefoldtech/zos pull request #219
Opened 2019-08-28 09:44 UTC by muhamadazmy

2019-08-28 11:41 UTC, zaibon reviewed
Can we make this flow depend on the success of the build flow ?
So we don't have to redo the all test/building phase ?

2019-08-28 11:42 UTC, zaibon requested changes

2019-08-28 11:42 UTC, zaibon commented on .github/workflows/flist.yml
> +    - name: Build FList
add an extra space here for readability.

2019-08-28 11:42 UTC, zaibon commented on .github/workflows/flist.yml
> +    - name: Build FList
shouldn't you have a `if: success()` here ?

2019-08-29 14:13 UTC, zaibon submitted a review, later dismissed
This LGTM.
But we also need a way to notify upgraded of the current version before it starts otherwise it will try to re-apply some update.
Check at https://github.com/threefoldtech/zosv2/blob/master/modules/upgrade/upgrade.go#L65 to see how upgraded check the current version

2019-08-29 14:16 UTC, zaibon commented
And the documentation around live upgrade also needs to be updated to reflect the new way of working.

2019-09-08 10:58 UTC, muhamadazmy commented
> But we also need a way to notify upgraded of the current version before it starts otherwise it will try to re-apply some update.

This PR is not related to `upgraded` or the update life cycle. This only configure the actions to auto-build the flist with all the binaries.

It also fixes a small issue in networkd that makes the network not work if the interfaces already have IP. (if the internet service from the 0-initramfs is working)

2019-09-08 11:15 UTC, zaibon commented
Then only the build a scripts need to be part of this PR. And we need to wait to get have the rest of the life cycle changed before we change the initramfs and introduce the internet service.

2019-09-09 09:22 UTC, muhamadazmy commented
> Then only the build a scripts need to be part of this PR. And we need to wait to get have the rest of the life cycle changed before we change the initramfs and introduce the internet service.

I believe I am not following on what u mean. Merging this PR here will not break the current build or change the image by anyhow (there is another PR on 0-initramfs) that **SHOULD NOT** be merged until we have the full cycle in place.

The next action we need to add here is to update version server with the correct flist name to use. then we can work on the upgraded daemon to use this new flist instead.

2019-09-09 15:35 UTC, zaibon commented
Yeah I went over the changes again an indeed. Nothing beaks here. I thought the addresses deletion happened after the bootstrap. That's not the case.
Does zinit stop on a non existing service doesn't return an error though?

2019-09-12 12:03 UTC, zaibon approved these changes

2019-09-12 12:07 UTC, merged