Move all rmb handlers to api-gateway
threefoldtech/zos pull request #2223
Opened 2024-03-07 09:19 UTC by AbdelrahmanElawady

### Description

Move all rmb handlers to api-gateway and use `peer.Router` instead of using `rmb-peer` binary.

### Changes

- All defined handlers and endpoints are now found under `pkg/api-gateway`.
- Unimplemented endpoints reply immediately that it's not implemented.

### Related Issues

- #2200 

### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstring

2024-03-13 12:52 UTC, muhamadazmy requested changes
Amazing job Abderahman. I only have few comments below. We need to also make this is well tested before we deploy to devnet.

2024-03-13 12:52 UTC, muhamadazmy commented on cmds/modules/api_gateway/main.go
> +		peer.WithRelay(environment.MustGet().RelayURL[0]),
We need to support having multiple relays. This is probably need to be modified in the sdk peer already.

2024-03-13 12:52 UTC, muhamadazmy commented on pkg/api_gateway/network.go
> +func (g *apiGateway) networkInterfacesHandler(ctx context.Context, payload []byte) (interface{}, error) {
I am just wondering if this logic should be part of the api, or networkd. I mean the api here shows understanding of the internals of some network internals. 

Just a thought, no need to modify it immediately

2024-03-13 12:52 UTC, muhamadazmy commented on cmds/modules/noded/main.go
> +	server.Register(zbus.ObjectID{Name: "host", Version: "0.0.1"}, perfMon)
isn't this a double register of the object `host` ?

2024-03-13 12:52 UTC, muhamadazmy commented on cmds/modules/noded/main.go
> +	server.Register(zbus.ObjectID{Name: "host", Version: "0.0.1"}, perfMon)
check the return error from register. this should return an error because you trying to register an object with the same id

2024-03-13 13:02 UTC, AbdelrahmanElawady commented on pkg/api_gateway/network.go
> +func (g *apiGateway) networkInterfacesHandler(ctx context.Context, payload []byte) (interface{}, error) {
I think it's mostly preparing input for networkd and parsing its output so it isn't really a lot of networking logic, that's why I didn't move it.

2024-03-13 13:03 UTC, AbdelrahmanElawady commented on cmds/modules/api_gateway/main.go
> +		peer.WithRelay(environment.MustGet().RelayURL[0]),
yep, it's already being done [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/917)

2024-05-22 12:43 UTC, ashraffouda approved these changes, later dismissed

2024-05-24 11:14 UTC, muhamadazmy approved these changes

2024-05-24 11:14 UTC, merged