test internet connection against hub.grid.tf
threefoldtech/zos pull request #2224
Opened 2024-03-07 11:58 UTC by Eslam-Nawara

### Description

test internet connection against hub.grid.tf

### Changes

add new connectivity test against hub.grid.tf in internet pkg

### Related Issues

- #2188 

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2024-03-07 12:01 UTC, xmonader commented on cmds/internet/main.go
> +		con, err := net.Dial("tcp", "hub.grid.tf:http")
Should we retry that maybe 3 times? @muhamadazmy @Eslam-Nawara

2024-03-18 12:25 UTC, muhamadazmy commented on cmds/internet/main.go
> +		con, err := net.Dial("tcp", "hub.grid.tf:http")
the entire function is retried forever anyway, until it succeeds

2024-03-18 12:26 UTC, muhamadazmy approved these changes

2024-03-18 12:32 UTC, muhamadazmy requested changes
The branch name causes the build to fail. I also can't manage to checkout the branch locally in my repo.

2024-03-18 12:32 UTC, muhamadazmy commented on cmds/internet/main.go
> +		con, err = net.Dial("tcp", "bootstrap.grid.tf:http")
Why not instead of copying the code you do that in loop instead 

```go
 for _, address := range []string{"bootstrap.grid.tf:http", "hub.grid.tf:http"} {
    //try to dial or return on error
    // close connection
}
```

this way u don't have to copy same code

2024-03-18 12:40 UTC, closed without merging