Main uncompress kernel
threefoldtech/zos pull request #2252
Opened 2024-04-01 21:59 UTC by rawdaGastan

### Related Issues

- https://github.com/threefoldtech/zos/issues/2236

2024-04-02 00:06 UTC, xmonader commented on pkg/primitives/vm/decompress_kernel.go
> +func isValidELFKernel(KernelImagePath string) error {
I think we can use debug/elf https://pkg.go.dev/debug/elf

2024-04-16 10:22 UTC, muhamadazmy requested changes

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/decompress_kernel.go
> +func tryDecompressKernel(KernelImagePath string) error {
why argument name is starting with an UpperCase ?

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/decompress_kernel.go
> +			f, err := os.Create(KernelImagePath)
you need to close this file

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/decompress_kernel.go
> +	tmpFile, err := os.CreateTemp("/tmp", "vmlinux-")
according to the docs. you should set `dir` (first argument) to empty string `""` to use the default tmp directory. It's better than setting it up explicitly imho

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/decompress_kernel.go
> +	defer os.Remove(tmpFile.Name())
The close has to happen first then deleting right ?
so this has to be in the opposite order. 

Or better 

```suggestion
        defer func() {
            tmpFile.Close()
            or.Remove(tmpFile.Name())
        }
```

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/utils.go
> +		if err != nil {
Just some cosmetics but i prefer always to do:

```go 
if err := functionThatMightFail(); err != nil {
   // handle error
}
```
Go error handling is already annoying, so this makes it a little bit compact

2024-04-16 10:22 UTC, muhamadazmy commented on pkg/primitives/vm/decompress_kernel.go
> +		// },
This function should still be there, with an implementation that only return error. But we can then return a clear error that we don't support lzop

2024-04-17 13:19 UTC, muhamadazmy approved these changes

2024-04-17 13:21 UTC, merged