push the integrity error to zui
threefoldtech/zos pull request #2424
Opened 2024-09-19 11:18 UTC by Omarabdul3ziz

- https://github.com/threefoldtech/zos/issues/2409

2024-09-22 07:09 UTC, muhamadazmy requested changes
Please also check why CI is failing

2024-09-22 07:09 UTC, muhamadazmy commented on cmds/modules/provisiond/main.go
> +		fmt.Errorf("integrity check failed, resetting rrd db stderr=%s: %w", buf.String(), err).Error(),
I think you can directly use `fmt.Stringf` instead . You going to lose the error cause anyway once u get the string.

2024-09-25 09:29 UTC, ashraffouda approved these changes

2024-09-25 12:40 UTC, muhamadazmy approved these changes

2024-09-26 10:51 UTC, merged