init node location updater
threefoldtech/zos pull request #2427
Opened 2024-09-22 14:25 UTC by Omarabdul3ziz

- add updater package
- expose GetState from registerer
- fix longitude spelling
- https://github.com/threefoldtech/zos/issues/2401

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2024-09-22 15:23 UTC, muhamadazmy requested changes
While i am not sure why zos needs to update location every 24 hours i don't believe this is the right way.

The registration service should be the only service to issue an update node (or create node) start to update the node outside this context can lead to unmanaged and hard to debug code.

Registration service already has a mechanism to update the node when some changes are detected (like ip change) and i think this should be included there

2024-09-23 11:49 UTC, Omarabdul3ziz commented
the issue is updates happen to some ips on the MaxMind database it may be a change in the country name from English chars to native chars like `Turkey` > `Türkiye` or the country name changed.

the suggestion was to update the node location periodically. since the changes in the database aren't frequent i thought once a day is a good period to check.

i moved the code for update location to be part of the register package

2024-09-26 11:28 UTC, muhamadazmy requested changes

2024-09-26 11:28 UTC, muhamadazmy commented on pkg/registrar/registrar.go
> +			if err := r.updateLocation(ctx, cl); err != nil {
Code in general looks way better. But why just not call `register()` here. It already collects the location, then compare if the node information has changed before calling update.

2024-10-09 07:45 UTC, muhamadazmy approved these changes

2024-10-09 07:48 UTC, merged