only allow deployments of verified users
threefoldtech/zos pull request #2445
Opened 2024-10-24 12:22 UTC by Eslam-Nawara

### Description

only allow deployments of verified users

### Related Issues

- #2444 

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2024-10-24 12:47 UTC, Eslam-Nawara commented
This pr would depend on the deployment of kyc server implemented [here](https://github.com/threefoldtech/tfgrid-kyc-verifier/pull/4) having this [requirements](https://github.com/threefoldtech/tfgrid-kyc-verifier/issues/5#issuecomment-2434853707), **it should not be merged before the deployment of the server with the required endpoint**

Merging the pr would cause that no unverified user would be able to use any zos3 to deploy any solution, **so it shouldn't be merged before the dashboard has a way to verify the twins**

Also we need to verify the twin used in github workflows so the test can run deployments

2024-10-24 13:14 UTC, xmonader commented on pkg/gridtypes/deployment.go
> +	verificationServiceURL := "https://kyc1.gent01.dev.grid.tf/api/v1/status"
this url should be retrieved from stack information

2024-10-30 10:24 UTC, ashraffouda submitted a review, later dismissed

2024-10-30 10:34 UTC, muhamadazmy requested changes, later dismissed

2024-10-30 10:34 UTC, muhamadazmy commented on pkg/provision/engine.go
> +	}
You can create a json Decoder with the body and hence you will not have to read it in memory first

2024-10-30 10:34 UTC, muhamadazmy commented on pkg/provision/engine.go
> +	status = "FAILED"
Please use a const instead. If possible values can only be success/failure then it's better to use a boolean maybe

Define a new type alias so it's not confused with actual strings

2024-10-30 10:34 UTC, muhamadazmy commented on pkg/provision/engine.go
> +		if getTwinVerificationStatus(twin) != "VERIFIED" {
Define constants or even better create a new type alias

2024-10-30 10:34 UTC, muhamadazmy commented on pkg/provision/engine.go
> +	}
This check needs to be done before you actually deserialize the body, no? If status is not okay a big chance the body is not json

2024-10-30 13:23 UTC, rawdaGastan approved these changes

2024-10-31 10:13 UTC, merged