identityd: send proper version during node registration
threefoldtech/zos pull request #324
Opened 2019-10-11 11:16 UTC by zaibon

fixes #313

2019-10-14 10:19 UTC, muhamadazmy requested changes
I don't really like this cross dependencies between modules. 
- zinit will start upgraded only when idendityd is running
- identityd will not register the node until upgraded is running.

Doing registration before even upgraded is done upgrading to latest will already register the node with "old" version, then may be later will re-register with latest version. 

IMHO: I think it's better (and makes more sense) to have both upgraded and identity merged in one single daemon. (upgraded)

Upgraded should do the following:
- On start, do update to latest version
- Register the node 
- Check new version available and update if necessary 
- On update, re-register the node.
...

2019-10-14 10:19 UTC, muhamadazmy commented on cmds/identityd/main.go
> +	upgrade := stubs.NewUpgradeModuleStub(redis)
I really don't like the idea that `identity` depends on upgrade for its operation. Even in zinit units, upgraded indirectly depends on identityd (which is considered a boot service).

2019-10-14 13:05 UTC, zaibon commented
I very much like the idea of merging things together, they are indeed very inter-depended.

2019-10-15 10:29 UTC, muhamadazmy approved these changes

2019-10-15 10:33 UTC, merged